---
  enable_render: False          # enable rendering. 
                                # NOTE: This setting is enabled regardless of testing or learning.
                                # It is not recommended to set this true during learning.
  # test parameters
  # NOTE: radius and observation parameters need to match genome being tested.
  test:
    genome: "01101001101000111101101010110001"
    iterations: 50

  # learning parameters
  learn:
    enable_seed: False          # set static seed or not
    seed: 42                    # seed value if seed is enabled
    tests: 4                    # number of tests per individual
    gen_max: 100                # number of generations before learning stops
                                # set to -1 to remove limit

  # evolution parameters
  evolution:
    max_pop: 100
    radius: 2                   # radius for cell evaluation
    uniform_percentage: 0.5     # percentage of population to keep after uniform selection
    truncation_percentage: 0.2  # percentage of population to keep after truncation selection
                                # truncation percentage needs to be lower than uniform percentage
    mutation_rate: 0.04         # mutation rate percentage
    # observation parameters
    observation:
      resolution: 10
      space: 2
      min_position: -2.4
      max_position: 2.4
      min_velocity: -3
      max_velocity: 3
      min_angle: -0.2095
      max_angle: 0.2095
      min_ang_velocity: -2
      max_ang_velocity: 2
...